inherit_gem:
  rubocop-mhenrixon:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Include:
    - "**/Rakefile"
    - "**/Gemfile"
    - "*.gemspec"
    - "bin/**/*"
    - "lib/**/*.rb"
    - "lib/**/*.rake"
    - "spec/**/*.rb"
  Exclude:
    - "Gemfile.lock"
    - "gemfiles/**/*"

Naming/FileName:
  Exclude:
    - lib/simplecov-sublime.rb

RSpec/MultipleMemoizedHelpers:
  Enabled: false
