inherit_gem:
  rubocop-mhenrixon:
    - config/default.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Include:
    - "**/Rakefile"
    - "**/Gemfile"
    - "*.gemspec"
    - "lib/**/*.rb"
    - "lib/**/*.rake"
    - "spec/**/*.rb"
  Exclude:
    - "Gemfile.lock"
    - "gemfiles/**/*"

Naming/FileName:
  Exclude:
    - lib/simplecov-oj.rb
