env:
  matrix:
    - COV=false
  global:
    - CC_TEST_REPORTER_ID=8ba417e8bf62f355529f4f11b42114f99e073459a7424e79845d64ab95e52b76
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
dist: bionic
sudo: required
language: ruby
cache:
  bundler: true
  directories:
     - /home/travis/.rvm/

before_install:
  - gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - gem update --system
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle install -j8 -r3

before_script:
  - ./cc-test-reporter before-build

script:
  - if [[ "${COV}" = "true" ]]; then bundle exec rubocop; fi;
  - bundle exec rspec spec

after_script:
  - if [[ "${COV}" = "true" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;

matrix:
  fast_finish: true
  include:
    - rvm: 2.6.5
      env: COV=true

notifications:
  email:
    recipients:
      - mikael@mhenrixon.com
